### ISSUE TITLE
Revert Patch 0002 when upstream fix is released

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-junipermist#195]
We implemented a patch that contains an upstream fix to work around an issue. The fix hasn't been released upstream yet, so we will want to remove this patch once the upstream fix is merged in. 

Upstream commit: https://github.com/Juniper/terraform-provider-mist/commit/a656744e713d15786900b4c08d76fe3afbf7f089

Patch PR: https://github.com/pulumi/pulumi-junipermist/pull/191

**Comment by guineveresaenger** [comment]
This patch has been reverted as part of https://github.com/pulumi/pulumi-junipermist/pull/205/files. Closing as done.
