### ISSUE TITLE
Fix resource identifier for upstream mist_site resource

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-junipermist#30]
### Describe what happened

It appears the mist_site resource, when generated downstream is [junipermist.device.Base](https://www.pulumi.com/registry/packages/junipermist/api-docs/device/base/) which I would expect to be `junipermist.site.Base` instead

### Sample program

N/A

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Thanks for reporting @zbuchheit, we've got a fix incoming in https://github.com/pulumi/pulumi-junipermist/pull/31
