### ISSUE TITLE
Error thrown when creating mist_site_wlan with isolation set

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-junipermist#49]
upstream: https://github.com/Juniper/terraform-provider-mist/issues/10

**Comment by zbuchheit** [comment]
this throws an error upstream, but for us appears as an empty perpetual diff when isolation is set to true

**Comment by iwahbe** [comment]
If the provider is fundamentally broken for this resource, then I think a perma-diff is the best we can expect for this resource in Pulumi.

We can take another look once the resource becomes usable in TF.

**Comment by zbuchheit** [comment]
agreed. I was more describing what behavior I was seeing for transparency and tracking. I don't think there is much action item for us on this issue.
